import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "@/components/styles/global.scss";
import { Roboto } from "next/font/google";
import { Providers } from "./provider";

const avenirNext = localFont({
  src: [
    {
      path: "./fonts/avenir-regular.otf",
      weight: "400",
      style: "normal",
    },

    {
      path: "./fonts/avenir-medium.otf",
      weight: "500",
      style: "medium",
    },

    {
      path: "./fonts/avenir-semibold.otf",
      weight: "700",
      style: "semibold",
    },

    {
      path: "./fonts/avenir-bold.otf",
      weight: "800",
      style: "bold",
    },
  ],
});

export const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  style: ["normal", "italic"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${avenirNext.className} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
